import type { ProductRow } from "@/types/database";

export const PLACEHOLDER_PRODUCTS: ProductRow[] = [
  {
    id: "placeholder-1",
    name: "Linh vật mini",
    description: null,
    price: 85000,
    availability: "in_stock",
    material: "PLA · nhiều màu",
    category: "decor",
    delivery_days_min: 3,
    delivery_days_max: 5,
    image_urls: null,
    stl_url: null,
    is_active: true,
    colors: ["#F472B6", "#3B82F6", "#F59E0B"],
    accent_bg: "var(--eoi-pink-light)",
    badge: "Hot",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: "placeholder-2",
    name: "Chậu cây geometric",
    description: null,
    price: 120000,
    availability: "in_stock",
    material: "PETG · trong suốt",
    category: "scene",
    delivery_days_min: 3,
    delivery_days_max: 5,
    image_urls: null,
    stl_url: null,
    is_active: true,
    colors: ["#111111", "#3B82F6"],
    accent_bg: "var(--eoi-blue-light)",
    badge: "New",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: "placeholder-3",
    name: "Giá đỡ AirPods",
    description: null,
    price: 65000,
    availability: "in_stock",
    material: "PLA matte",
    category: "office",
    delivery_days_min: 3,
    delivery_days_max: 5,
    image_urls: null,
    stl_url: null,
    is_active: true,
    colors: ["#F59E0B", "#F472B6"],
    accent_bg: "var(--eoi-amber-light)",
    badge: "Sale",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: "placeholder-4",
    name: "Móc khóa chữ cái",
    description: null,
    price: 45000,
    availability: "in_stock",
    material: "PLA",
    category: "gift",
    delivery_days_min: 3,
    delivery_days_max: 5,
    image_urls: null,
    stl_url: null,
    is_active: true,
    colors: ["#3B82F6", "#F472B6", "#F59E0B"],
    accent_bg: "var(--eoi-pink-light)",
    badge: null,
    created_at: new Date().toISOString(),
    updated_at: null,
  },
];
